# solver
solver: 'gurobi'
solver_options:
  gurobi:
    Threads: 0
    Method: 2
    BarHomogeneous: 1
    Crossover: 0
    BarConvTol: 0.0001
  cplex:
    solutiontype: 1

# Time
time:
  slice: ['2015-01-01T00:00', '2015-01-01T10:00']
  resolution: 1

# Space
region: "BENELUX"
add_offshore: True # ! if False, remove wind_offshore and wind_floating from RES technologies

# RES
res:
  include: False
  # Give which technology should be installed using each strategy
  strategies:
    from_files: []
    no_siting: []
    siting: []
    bus: ['wind_offshore', 'wind_onshore', 'pv_utility']

  # For strategy = from_files
  sites_dir: '20200414_214108'
  sites_fn: 'max_site_data.p'
  use_default_capacity: True

  # For strategy = siting or no siting
  # Various data layers to be taken into account in potential site selection.
  spatial_resolution: 0.5
  timeslice: ['2015-01-01T00:00', '2015-01-01T23:00']
  use_ex_cap: True
  limit_max_cap: True

  # For strategy = siting
  # Type of problem to be solved. Check resite/formulations for a full list.
  formulation: 'meet_RES_targets'
  formulation_params:
    perc_per_region : [0.1]
    time_resolution: 'hour'
  modelling: 'pyomo' # Choice of modelling language. Available: 'gurobipy', 'docplex' and 'pyomo'
  write_lp: False

# Conventional generation
dispatch:
  include: True
  tech: "ccgt"

# Nuclear
nuclear:
  include: True
  use_ex_cap: True # Whether to include existing cap
  extendable: False

# Battery
battery:
  include: True
  type: "Li-ion"

# Hydro
phs:
  include: True
  use_ex_cap: True
  extendable: False
  cyclic_sof: True

ror:
  include: True
  use_ex_cap: True
  extendable: False

sto:
  include: True
  use_ex_cap: True
  extendable: False
  cyclic_sof: True

# Emissions
co2_emissions:
  reference_year: 1990
  mitigation_factor: 0.8