name: pyggrid
channels:
  - defaults
  - conda-forge
  - ibmdecisionoptimization
  - http://conda.anaconda.org/gurobi
dependencies:
  - python
  - pip

  - pypsa
  - atlite

  - gdal==2.4.4

  - pycountry

  - xarray
  - dask
  - scikit-learn

  - PyYAML

  - shapely
  - geopandas
  - cartopy
  - powerplantmatching
  - geopy
  - geojson
  - libgdal

  - gurobi==8.1.1

  - pip:
      - dash==1.7.0
      - vresutils==0.3.1
      - git+https://github.com/FZJ-IEK3-VSA/geokit.git#egg=geokit
      - git+https://github.com/FZJ-IEK3-VSA/glaes.git#egg=glaes
      - cdsapi
      - docplex
      - cplex
      - windpowerlib