name: replan
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.6
  - pip
  - pypsa
  - gdal=2.4.4
  - pycountry
  - xarray
  - dask
  - scikit-learn
  - geopandas
  - geopy
  - xlrd
  - progressbar2
  - libwebp

  - pip:
      - git+https://github.com/FZJ-IEK3-VSA/geokit.git#egg=geokit
      - git+https://github.com/FZJ-IEK3-VSA/glaes.git#egg=glaes
      - windpowerlib
      - vresutils
