channels:
  - defaults
  - conda-forge
  - ibmdecisionoptimization
  - http://conda.anaconda.org/gurobi
dependencies:
  - python=3.6
  - pip

  - pypsa
  - atlite

  - gdal==2.4.4

  - pycountry

  - xarray
  - pandas=1.0.0
  - dask
  - scikit-learn

  - PyYAML

  - shapely
  - geopandas
  - cartopy
  - powerplantmatching
  - geopy
  - geojson
  - libgdal
  - unidecode
  - xlrd==1.2.0

  - gurobi==8.1.1

  - pip:
      - dash==1.7.0
      - vresutils==0.3.1
      - git+https://github.com/FZJ-IEK3-VSA/geokit.git#egg=geokit
      - git+https://github.com/FZJ-IEK3-VSA/glaes.git#egg=glaes
      - cdsapi
      - docplex
      - cplex
      - windpowerlib
