# model
keep_lp: False

# solver
solver: 'gurobi'
solver_options:
  # gurobi
  Threads: 0
  Method: 2
  BarHomogeneous: 1
  Crossover: 0
  BarConvTol: 1e-8
  # cplex
  # threads: 0
  # lpmethod: 1
  # solutiontype: 2
  # barrier convergetol: 1e-8

get_duals: False

# Time
time:
  slice: ['2018-01-01T00:00', '2018-01-01T23:00']
  resolution: 1

# Space
region: "BENELUX"
add_TR: False

# RES
res:
  include: False
  # Give which technology should be installed using each strategy
  strategies:
    no_siting: []
    siting: []
    bus: ['wind_offshore', 'pv_utility', 'pv_residential', 'wind_onshore']

  min_cap_pot: [0, 0, 0, 0]

  # For strategy = siting or no siting
  # Various data layers to be taken into account in potential site selection.
  spatial_resolution: 0.5
  timeslice: ['2018-01-01T00:00', '2018-01-01T23:00']
  use_ex_cap: True
  limit_max_cap: True

  # For strategy = siting
  modelling: 'pyomo' # Choice of modelling language. Available: 'gurobipy', 'docplex' and 'pyomo'
  solver: 'gurobi' # Choice of solver. Available: 'gurobi', 'cplex' and 'cbc'
  solver_options:
    # gurobi
    Threads: 0
    Method: 2
    BarHomogeneous: 1
    Crossover: 0
    BarConvTol: 1e-8
    # cplex:
    # solutiontype: 1
  write_lp: False
  write_log: False
  # Type of problem to be solved. Check resite for a full list.
  formulation: 'meet_RES_targets'
  formulation_params:
    perc_per_region: [0.32]
    time_resolution: 'hour'
  # Keeping files at the end of the run.
  keep_files: True

techs:
  dispatch:
    tech: "ccgt"

  # nuclear:
  #  use_ex_cap: True # Whether to include existing cap
  #  extendable: False

  battery:
    type: "Li-ion"

  phs:
    use_ex_cap: True
    extendable: False
    cyclic_sof: True

  ror:
    use_ex_cap: True
    extendable: False

  sto:
    use_ex_cap: True
    extendable: False
    cyclic_sof: True

functionalities:
  snsp:
    include: False
    share: 0.65
  curtailment:
    include: False
    strategy: ['economic', 10.] # ['technical', 0.], ['technical', 1.], ['economic', 0.], ['economic', 9999.]
  load_shed:
    include: False
  import_limit:
    include: False
    share: 0.5
  co2_emissions:
    include: True
    strategy: 'global' # country, global
    reference_year: 1990 # Flat reference across all countries for now.
    mitigation_factor: 0.9

non_eu:
  res:
    NA: ["pv_utility_noneu"]
    GL: ["wind_onshore_noneu"]
    IS: ["wind_onshore_noneu"]
