# MGA
mga:
  epsilons: [0.01, 0.1]
  link-whole: True
  link-bus: ['BE', 'NL']
  link-link: ['BE-NL']
  storage: True
  res-total: True
  res-sub: ['wind_onshore_national']

# Space
region: "BENELUX"

# Time
# Start time and end time for slicing the database.
time:
  slice: ['2016-01-01T00:00', '2016-01-01T23:00']
  resolution: 1
  agg_resolution: '2H'

# Lines
extension_multiplier: 2.0
p_max_pu: 0.7 # value based on Neumann

# RES
res:
  include: True
  techs: ['pv_utility_national', 'wind_onshore_national', 'wind_offshore_national']
  use_ex_cap: False
  limit_max_cap: True
  precision: 2

# Conventional generation
dispatch:
  include: True
  techs: ["ccgt", "ocgt"]

# Nuclear
nuclear:
  include: True
  use_ex_cap: True # Whether to include existing cap
  extendable: False

# Battery
battery:
  include: True
  type: "Li-ion"

# Hydro
phs:
  include: True
  use_ex_cap: True
  extendable: False
  cyclic_sof: True

ror:
  include: True
  use_ex_cap: True
  extendable: False

sto:
  include: True
  use_ex_cap: True
  extendable: False
  cyclic_sof: True

pyomo: False
functionalities:
  snsp:
    include: False
    share: 0.65
  curtailment:
    include: False
    strategy: ['economic', 10.] # ['technical', 0.], ['technical', 1.], ['economic', 0.], ['economic', 9999.]
  load_shed:
    include: True
  import_limit:
    include: False
    share: 0.5
  co2_emissions:
    include: True
    strategy: 'global' # country, global
    reference_year: 1990 # Flat reference across all countries for now.
    mitigation_factor: 0.99


# solver
solver: 'gurobi'
solver_options:
  # gurobi:
  # Threads: 0
  Method: 2
  # BarHomogeneous: 0
  # Crossover: 0
  # BarConvTol: 1.0e-8
  Presolve: 0
  # FeasibilityTol - feasibility of primal constraints (default : 10e-6)
  # OptimalityTol - feasibility of dual constraints
  # cplex:
  # threads: 0
  # lpmethod: 1
  # solutiontype: 2
  # barrier convergetol: 1e-8

  # cbc: 0

# model
keep_lp: True