# model
keep_lp: False

# solver
solver: 'gurobi'
solver_options:
  # gurobi
  Threads: 0
  Method: 2
  BarHomogeneous: 1
  Crossover: 0
  BarConvTol: 1.0e-8
  # cplex
  # threads: 0
  # lpmethod: 1
  # solutiontype: 2
  # barrier convergetol: 1e-8

get_duals: True

# Time
time:
  slice: ['2018-01-01T00:00', '2018-01-01T23:00']
  resolution: 1

# Space
region: "GBIE"
add_TR: False

# RES
res:
  include: True
  # Give which technology should be installed using each strategy
  techs: ['pv_residential', 'wind_offshore']
  strategy: 'siting'

  min_cap_pot: [0, 0]

  # For strategy = siting or no siting
  # Various data layers to be taken into account in potential site selection.
  spatial_resolution: 2.0
  timeslice: ['2018-01-01T00:00', '2018-01-01T23:00']
  use_ex_cap: True
  limit_max_cap: True

  # For strategy = siting
  # Type of problem to be solved. Check resite for a full list.
  formulation: 'min_cost_global'
  formulation_params:
    perc_per_region: [0.1, 0.1]
    perc_global: 1.0
    time_resolution: 'hour'
  modelling: 'gurobipy' # Choice of modelling language.
  solver: 'gurobi' # Choice of solver.
  solver_options:
    # gurobi
    Threads: 0
    Method: 2
    BarHomogeneous: 1
    Crossover: 0
    BarConvTol: 1e-8
    # cplex:
    # solutiontype: 1
  write_lp: False
  write_log: False
  # Keeping files at the end of the run.
  keep_files: True

techs:
  dispatch:
    tech: "ccgt"

  #nuclear:
  #  use_ex_cap: True # Whether to include existing cap
  #  extendable: False

  battery:
    type: "Li-ion"

  phs:
    use_ex_cap: True
    extendable: False
    cyclic_sof: True

  ror:
    use_ex_cap: True
    extendable: False

  sto:
    use_ex_cap: True
    extendable: False
    cyclic_sof: True

functionalities:
  snsp:
    include: False
    share: 0.65
  curtailment:
    include: False
    strategy: ['economic', 10.] # ['technical', 0.], ['technical', 1.], ['economic', 0.], ['economic', 9999.]
  load_shed:
    include: False
  import_limit:
    include: False
    share: 0.5
  co2_emissions:
    include: False
    strategy: 'global' # country, global
    reference_year: 1990 # Flat reference across all countries for now.
    mitigation_factor: 0.9

non_eu:
  #NA: ["pv_utility_noneu"]
  #GL: ["wind_onshore_noneu"]
  IS: ["wind_onshore_noneu"]
